function [kp_fit_1_a, ki_fit_1_a, kd_fit_1_a,  ...
          kp_fit_1_b, ki_fit_1_b, kd_fit_1_b, ...
          kp_fit_2_a, ki_fit_2_a, kd_fit_2_a, ...
          kp_fit_2_b, ki_fit_2_b, kd_fit_2_b] = unpack_ganhos(pack_ganhos)

[kp_fit_1_a, ki_fit_1_a, kd_fit_1_a,  ...
          kp_fit_1_b, ki_fit_1_b, kd_fit_1_b, ...
          kp_fit_2_a, ki_fit_2_a, kd_fit_2_a, ...
          kp_fit_2_b, ki_fit_2_b, kd_fit_2_b] = pack_ganhos{:,:};

end